# Generated by Django 3.1.1 on 2020-10-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=40)),
                ('expires_in', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EazzyPushRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_country_code', models.CharField(max_length=2)),
                ('customer_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('api_transaction_reference', models.CharField(max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=12)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_description', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('is_posted', models.BooleanField(default=False)),
                ('transaction_status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eazzypaypush Requests',
                'db_table': 'tbl_eazzypay_push',
            },
        ),
        migrations.CreateModel(
            name='LipanampesaRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('customer_country_code', models.CharField(max_length=2)),
                ('api_transaction_reference', models.CharField(max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=12, unique=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_description', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(null=True)),
                ('transaction_status', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'LipaNaMpesaOnline Requests',
                'db_table': 'tbl_lipanampesaonline_push',
            },
        ),
    ]
