# Generated by Django 3.1.1 on 2020-09-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EazzyPushRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_country_code', models.CharField(max_length=2)),
                ('customer_phone_number', models.BigIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_reference', models.CharField(max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tbl_eazzypay_push',
            },
        ),
    ]
