# Generated by Django 3.1.1 on 2020-10-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eazzypushrequest',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eazzypushrequest',
            name='transaction_status',
            field=models.CharField(default='done', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eazzypushrequest',
            name='transaction_reference',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='lipanampesarequest',
            name='transaction_reference',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
