# Generated by Django 3.1.1 on 2020-09-28 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0002_eazzypushrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eazzypushrequest',
            options={'verbose_name_plural': 'Eazzypaypush Requests'},
        ),
        migrations.AddField(
            model_name='eazzypushrequest',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eazzypushrequest',
            name='transaction_date',
            field=models.DateTimeField(null=True),
        ),
    ]
