# Generated by Django 3.1.1 on 2020-10-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0005_auto_20200929_0946'),
        ('equitycore', '0005_lipanampesarequest'),
    ]

    operations = [
    ]
