# Generated by Django 3.1.1 on 2020-10-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0005_lipanampesarequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipanampesarequest',
            name='transaction_reference',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
