# Generated by Django 3.1.1 on 2020-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0006_auto_20201006_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipanampesarequest',
            name='transaction_status',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
