# Generated by Django 3.1.1 on 2020-10-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equitycore', '0007_lipanampesarequest_transaction_status'),
        ('equitycore', '0006_merge_20201003_1031'),
    ]

    operations = [
    ]
